# Generated by Django 4.1.1 on 2022-09-08 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankingAuthor', models.FloatField(default=0.0)),
                ('authorUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=82, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wahl', models.CharField(choices=[('Artikel', 'Статья'), ('Nachricht', 'Новость')], default='Artikel', max_length=16)),
                ('titel_name', models.CharField(max_length=212)),
                ('text', models.TextField()),
                ('ranking', models.FloatField(default=0.0)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News_Portal.author')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryBeziehung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News_Portal.category')),
                ('PostBeziehung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News_Portal.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='postCategory',
            field=models.ManyToManyField(through='News_Portal.PostCategory', to='News_Portal.category'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField()),
                ('time_comment', models.DateTimeField(auto_now_add=True)),
                ('comment_ranking', models.FloatField(default=0.0)),
                ('commentPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News_Portal.post')),
                ('commentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
